////////////////////////////////////////////////////////////////////////////////
/// DISCLAIMER
///
/// Copyright 2025 SereneDB GmbH, Berlin, Germany
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///     http://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///
/// Copyright holder is SereneDB GmbH, Berlin, Germany
////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <cstdint>
#include <string>

#include "catalog/identifiers/identifier.h"
#include "catalog/identifiers/object_id.h"
#include "catalog/object.h"
#include "catalog/types.h"

namespace vpack {
class Builder;
}  // namespace vpack

namespace sdb::catalog {

enum class ObjectCategory : uint8_t {
  Collection = 1,
  View = 2,
  Function = 3,
  Virtual = 4,
  Role = 5,
};

class LogicalObject : public SchemaObject {
 public:
  ObjectCategory category() const noexcept { return _category; }

  virtual void WriteProperties(vpack::Builder& build) const = 0;

  ObjectId GetDatabaseId() const noexcept { return _db_id; }

  template<typename V>
  bool Is(V v) const noexcept;

 protected:
  // 'id' autogenerated IFF 'id' == 0
  LogicalObject(ObjectCategory category, ObjectId database_id, ObjectId id,
                std::string&& name);

  const ObjectId _db_id;
  const ObjectCategory _category;
};

}  // namespace sdb::catalog
